### ISSUE TITLE
Unhandled error during deletion from the favorites list

### ISSUE THREAD

**Issue by etehtsea** [vickyqjx/simple_map#2]
<img width="1071" alt="Screenshot 2020-05-02 at 19 22 08" src="https://user-images.githubusercontent.com/100999/80864100-8dd38500-8caa-11ea-8fb3-f18a8750926c.png">

Steps to reproduce:
- stop backend;
- attempt to delete item from the favorites list

What do you think about returning error message like "Service is temporary unavailable" to the user?

**Comment by vickyqjx** [comment]
Yes,  that's a very nice point. I have added the error handling for this scenario, and display the "Service is temporary unavailable" message to the user. 

Here's the commit for the change.
[https://github.com/vickyqjx/simple_map/commit/ad4cf4657b5c8d0baadf329d6036b0a3e4b57c56](url)

Thanks

**Comment by vickyqjx** [comment]
Thanks, @etehtsea.  That's a very good point.
I have added the error handling for this scenario, and display the message "Service is temporary unavailable" to the user. 

Here's the code change:
[https://github.com/vickyqjx/simple_map/commit/ad4cf4657b5c8d0baadf329d6036b0a3e4b57c56](url)

**Comment by etehtsea** [comment]
@vickyqjx awesome, thanks!
