### ISSUE TITLE
Client code consistency

### ISSUE THREAD

**Issue by ipuchkov** [vickyqjx/simple_map#3]
In order to simplify maintainability of client app codebase I would suggest to rewrite all frontend components from ES6 JS to TypeScript.

**Comment by vickyqjx** [comment]
@ipuchkov 
I have updated all frontend components to TypeScript. [https://github.com/vickyqjx/simple_map/commit/6a0b7bf0b7c93bb70c1150208172cc9fb21012cb](url)

**Comment by ipuchkov** [comment]
@vickyqjx cool, thank you!
