### ISSUE TITLE
Absence of user-friendly errors when geo API isn't available

### ISSUE THREAD

**Issue by ipuchkov** [vickyqjx/simple_map#4]
Currently if geolocation API isn't available client doesn't show any errors to user. So it is not obvious that something went wrong.

#### Steps to reproduce:
* Block access to geo api (eg. forward to localhost in hosts file)
* Perform search request on frontend

**Comment by vickyqjx** [comment]
@ipuchkov 
Thanks for pointing out.

Added the error message when geo API isn't available.
<img width="770" alt="Screen Shot 2020-05-03 at 4 28 26 pm" src="https://user-images.githubusercontent.com/1001222/80907582-ae0f4c80-8d5b-11ea-8bc7-1606a88739b3.png">

Here is the code change:
https://github.com/vickyqjx/simple_map/commit/f3e6961227967409abe673b7d8095e5395f9cdd2
